# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 19:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20180709_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='lastchecked',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
